// Generated by CoffeeScript 1.9.1
(function() {
  var config;

  config = {
    host: 'http://shostream.com',
    defaultPort: 5000,
    memcached: {
      enabled: true,
      defaultHost: 'localhost',
      defaultPort: 11211,
      maxValue: 2097152,
      connectRetries: 5,
      key: 'shostream.com'
    },
    logentries: {
      enabled: false,
      token: 'YOUR_LOGENTRIES_TOKEN_HERE'
    },
    getParamWhitelist: ['page']
  };

  module.exports = config;

}).call(this);
